apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-review-app
  name: book-review-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: book-review-app
  template:
    metadata:
      labels:
        app: book-review-app
    spec:
      containers:
        - image: book-review-app
          imagePullPolicy: Never
          name: book-review-app
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-review-app
  name: book-review-app
  namespace: book-review-app
spec:
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
  selector:
    app: book-review-app
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: book-review-app
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              service:
                name: book-review-app
                port:
                  number: 5002
            path: /
            pathType: Prefix
---
