apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-mockup
  namespace: argocd-mockup
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/dev
    repoURL: https://github.com/Pokepasaj/mockup.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
